apiVersion: apps/v1
kind: Deployment

metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp

  replicas: 1
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: sandrodev/node-ts-app:1.7
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "500m"

          startupProbe:
            httpGet:
              path: /healthz
              port: 4000
            periodSeconds: 3
            failureThreshold: 20

          readinessProbe:
            httpGet:
              path: /healthz
              port: 4000
            periodSeconds: 3
            failureThreshold: 1
            # initialDelaySeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
            # initialDelaySeconds: 10

          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: nodeapp-env

          volumeMounts:
            - mountPath: "/usr/src/app"
              name: "nodeapp-volume"

      volumes:
        - name: "nodeapp-volume"
          persistentVolumeClaim:
            claimName: "nodeapp-pvc"
