apiVersion: apps/v1
kind: Deployment

metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp

  replicas: 2
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: sandrodev/node-ts-app:1.5
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000
          env:
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: nodeapp-env
                  key: USER
            - name: EMAIL
              valueFrom:
                configMapKeyRef:
                  name: nodeapp-env
                  key: EMAIL
